def err():
    print('raise error')
    raise Exception('a')
